export enum EventDataType {
    GUILD_DATA = 'GUILD_DATA',
    USER_DATA = 'USER_DATA',
    MESSAGE_DATA = 'MESSAGE_DATA',
    EVENT_DATA = 'EVENT_DATA',
    MEMBER_ANNIVERSARY_ROLE_DATA = 'MEMBER_ANNIVERSARY_ROLE_DATA',
}
