export enum HelpOption {
    GENERAL = 'GENERAL',
    BLACKLIST = 'BLACKLIST',
    CONFIG = 'CONFIG',
    MESSAGE = 'MESSAGE',
    TRUSTED_ROLE = 'TRUSTED_ROLE',
    EVENT = 'EVENT',
    MEMBER_ANNIVERSARY_ROLE = 'MEMBER_ANNIVERSARY_ROLE',
    PREMIUM = 'PREMIUM',
    PERMISSIONS = 'PERMISSIONS',
}
