export enum ListType {
    BIRTHDAY = 'BIRTHDAY',
    MEMBER_ANNIVERSARY = 'MEMBER_ANNIVERSARY',
    SERVER_ANNIVERSARY = 'SERVER_ANNIVERSARY',
    EVENT = 'EVENT',
    USER_SPECIFIC_BIRTHDAY = 'USER_SPECIFIC_BIRTHDAY',
    USER_SPECIFIC_MEMBER_ANNIVERSARY = 'USER_SPECIFIC_MEMBER_ANNIVERSARY',
}
