export enum Procedure {
    CustomMessages_Add = 'CustomMessages_Add',
    CustomMessages_Remove = 'CustomMessages_Remove',
    CustomMessages_Clear = 'CustomMessages_Clear',
    CustomMessages_Get = 'CustomMessages_Get',
    CustomMessages_GetList = 'CustomMessages_GetList',
    Guild_Get = 'Guild_Get',
    Guild_GetAll = 'Guild_GetAll',
    Guild_UpdateBirthdayChannel = 'Guild_UpdateBirthdayChannel',
    Guild_UpdateBirthdayRole = 'Guild_UpdateBirthdayRole',
    Guild_UpdateTrustedRole = 'Guild_UpdateTrustedRole',
    Guild_UpdateMessageTime = 'Guild_UpdateMessageTime',
    Guild_UpdateMentionSetting = 'Guild_UpdateMentionSetting',
    Guild_UpdateUseEmbed = 'Guild_UpdateUseEmbed',
    Guild_UpdateTrustedPreventsMessage = 'Guild_UpdateTrustedPreventsMessage',
    Guild_UpdateTrustedPreventsRole = 'Guild_UpdateTrustedPreventsRole',
    Guild_SetupMessage = 'Guild_SetupMessage',
    Guild_SetupTrusted = 'Guild_SetupTrusted',
    Guild_AddOrUpdate = 'Guild_AddOrUpdate',
    User_AddOrUpdate = 'User_AddOrUpdate',
    User_Get = 'User_Get',
    User_GetAll = 'User_GetAll',
    User_GetFullList = 'User_GetFullList',
    User_GetBirthdays = 'User_GetBirthdays',
}
